/**
 * Lightweight report exporter — no extra dependencies.
 *  - PDF: opens a styled print window (Save as PDF).
 *  - Word: downloads an editable, Word-compatible .doc (HTML) so users can tweak it.
 * Callers supply a title, optional subtitle and a `body` of HTML (headings + tables).
 */

export interface ReportInput {
  title: string
  subtitle?: string
  body: string // HTML — typically <h2> + <table> blocks
  css?: string // extra CSS appended to the base stylesheet (e.g. the payslip layout)
  landscape?: boolean
  filenameBase: string
  /** Hide the logo/title header — for bodies that print their own per-page heading. */
  noHeader?: boolean
  /** Hide the "Generated by INZU Workstation" line — payslips are issued documents. */
  noFooter?: boolean
}

/** Escape user-supplied text for safe HTML embedding. */
export function esc(v: unknown): string {
  return String(v ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!))
}

async function toDataURL(url: string): Promise<string> {
  try {
    const res = await fetch(url)
    if (!res.ok) return ''
    const blob = await res.blob()
    return await new Promise<string>((resolve) => {
      const fr = new FileReader()
      fr.onload = () => resolve(String(fr.result))
      fr.onerror = () => resolve('')
      fr.readAsDataURL(blob)
    })
  } catch { return '' }
}

let logoCache: string | undefined
/** The INZU logo as a data URL, cached. Empty string if it can't be loaded. */
export async function inzuLogo(): Promise<string> {
  if (logoCache === undefined) logoCache = await toDataURL(`${window.location.origin}/logo.png`)
  return logoCache
}

const BASE_CSS = `
  body{font-family:Arial,Helvetica,sans-serif;color:#0F1B33;}
  h1{font-size:18px;margin:0;}
  .subt{color:#6B7280;font-size:12px;margin:3px 0 0;}
  .rhead{display:flex;align-items:center;gap:16px;border-bottom:2px solid #0F1B33;padding-bottom:12px;margin-bottom:14px;}
  .rhead img{max-height:54px;max-width:170px;object-fit:contain;}
  h2{font-size:13px;margin:16px 0 6px;color:#0F1B33;}
  table{border-collapse:collapse;width:100%;font-size:11px;margin-bottom:8px;}
  th,td{border:1px solid #d0d4dc;padding:5px 8px;text-align:left;}
  th{background:#0F1B33;color:#fff;font-weight:600;}
  td.num,th.num{text-align:right;}
  tr.tot td{background:#F8E7D7;font-weight:700;}
  .kv{display:flex;flex-wrap:wrap;gap:8px 22px;font-size:12px;margin:6px 0 12px;}
  .kv b{color:#0F1B33;}
  .muted{color:#6B7280;font-size:10px;margin-top:14px;}
`

function headerHtml(logo: string, title: string, subtitle?: string): string {
  return `<div class="rhead">${logo ? `<img src="${logo}" alt="INZU">` : ''}<div><h1>${esc(title)}</h1>${subtitle ? `<p class="subt">${esc(subtitle)}</p>` : ''}</div></div>`
}

/** Open a print window for PDF export. */
export async function exportReportPDF(r: ReportInput): Promise<void> {
  const w = window.open('', '_blank', 'width=1000,height=760')
  if (!w) { alert('Allow pop-ups to export the PDF.'); return }
  const logo = await inzuLogo()
  const page = `@page{size:A4 ${r.landscape ? 'landscape' : 'portrait'};margin:12mm;}`
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>${esc(r.title)}</title>
    <style>${BASE_CSS}${r.css ?? ''}${page}@media print{body{margin:0;}}</style></head>
    <body onload="setTimeout(function(){window.print()},80)">
      ${r.noHeader ? '' : headerHtml(logo, r.title, r.subtitle)}
      ${r.body}
      ${r.noFooter ? '' : `<p class="muted">Generated by INZU Workstation · ${new Date().toLocaleString()}</p>`}
    </body></html>`
  w.document.open(); w.document.write(html); w.document.close()
}

/** Download an editable Word (.doc) version. */
export function exportReportWord(r: ReportInput): void {
  const orient = r.landscape ? 'landscape' : 'portrait'
  const size = r.landscape ? '29.7cm 21cm' : '21cm 29.7cm'
  // No logo image in Word — base64 images render unreliably; keep a clean text header.
  const html = `<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40">
    <head><meta charset="utf-8"><style>${BASE_CSS}${r.css ?? ''}@page{size:${size};mso-page-orientation:${orient};margin:1.2cm;}</style></head>
    <body>${r.noHeader ? '' : headerHtml('', r.title, r.subtitle)}${r.body}</body></html>`
  const blob = new Blob(['﻿', html], { type: 'application/msword' })
  const a = document.createElement('a')
  a.href = URL.createObjectURL(blob)
  a.download = `${r.filenameBase}.doc`
  document.body.appendChild(a)
  a.click()
  a.remove()
  setTimeout(() => URL.revokeObjectURL(a.href), 30_000)
}
